# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_text',
            field=models.CharField(default='Aliquam iaculis ornare tristique. Phasellus ullamcorper tristique est, ac dictum quam sagittis ut.', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collections_text',
            field=models.CharField(default='Aliquam iaculis ornare tristique. Phasellus ullamcorper tristique est, ac dictum quam sagittis ut.', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_text',
            field=models.CharField(default='Aliquam iaculis ornare tristique. Phasellus ullamcorper tristique est, ac dictum quam sagittis ut.', max_length=150),
        ),
    ]
