# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0003_auto_20170712_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(help_text='ideal dimensions are 1440x630px, please optimize image size too!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
