# Generated by Django 2.2.9 on 2020-03-12 19:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_image_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='collections_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
