# Generated by Django 3.2.15 on 2022-08-30 20:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepg_richtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_link',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collections_link',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_link',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True),
        ),
    ]
