# Generated by Django 4.0.10 on 2024-02-21 22:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us_link',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='collections_link',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_link',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
