# Generated by Django 2.0.2 on 2018-10-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_page-ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitartwork',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('html', 'Embed code (HTML)')], default='image', help_text='Used to determines the way this work appears in the gallery.', max_length=20),
        ),
    ]
