# Generated by Django 2.1.5 on 2019-02-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_exhib-video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitartwork',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('html', 'Embed code (HTML)')], default='image', help_text='Used to determines the way this work appears in the gallery.', max_length=20),
        ),
    ]
