# Generated by Django 2.1.7 on 2019-03-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_exhib_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitpage',
            name='gallery_columns',
            field=models.IntegerField(default=2, help_text='Recommended to be 2 or 3. Other numbers may cause odd layouts.'),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='gallery_spacing',
            field=models.IntegerField(default=4, help_text='Horizontal padding (in pixels) between works in the gallery.'),
        ),
        migrations.AddField(
            model_name='exhibitpage',
            name='main_body_font',
            field=models.CharField(choices=[('serif', 'Default (The Serif/Merriweather)'), ('sans-serif', 'Sans Serif (Brown/Raleway)'), ('stencil', 'Stencil (Le Corbusier/Stardos Stencil)'), ('monospace', 'Monospace (Consolas)')], default='serif', help_text='Font applied to the Description & other details (location/reception/etc.) below.', max_length=50),
        ),
    ]
