# Generated by Django 2.2.11 on 2020-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0010_LinkedImageBlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='One "Featured" Exhibit shows up on the Libraries home page.'),
        ),
    ]
