# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
                ('html', models.TextField(blank=True, help_text='Text of gram with hashtags & usernames converted to <a> links')),
                ('image', models.URLField()),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
