# Generated by Django 2.1.3 on 2018-11-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_ig-oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='ig_id',
            field=models.TextField(default='UNKNOWN'),
        ),
    ]
