# Generated by Django 2.2.9 on 2020-01-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_ig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
