# Generated by Django 2.2.11 on 2020-03-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_insta_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramoauthtoken',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
