# Generated by Django 2.2.13 on 2021-02-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_insta_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram',
            old_name='image',
            new_name='image_url',
        ),
    ]
