# Generated by Django 2.2.13 on 2021-02-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('instagram', '0006_ig_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='image',
            field=models.ForeignKey(help_text='downloaded Instagram image', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
