# Generated by Django 4.2.17 on 2025-01-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("instagram", "0007_insta_wagtailimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ig_app_id",
                    models.TextField(
                        default="936619743392459",
                        help_text="This is necessary for an HTTP header sent to Instagram or else IG will respond with a 400 error when we try to obtain our account's data.",
                        verbose_name="x-ig-app-id header",
                    ),
                ),
                (
                    "instagram_account",
                    models.TextField(
                        default="ccalibraries",
                        help_text="Our Instagram account username (with no leading '@').",
                        max_length=30,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
