# Generated by Django 4.2.17 on 2025-01-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0008_igsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagram",
            name="accessibility_caption",
            field=models.TextField(
                blank=True,
                help_text="Instagram's accessibility caption (AI-generated if we do not provide one)",
            ),
        ),
        migrations.AddField(
            model_name="instagram",
            name="json",
            field=models.JSONField(
                blank=True, help_text="Raw JSON data from Instagram API", null=True
            ),
        ),
        migrations.AlterField(
            model_name="instagram",
            name="date_added",
            field=models.DateTimeField(
                auto_now=True, help_text="Date added to Wagtail"
            ),
        ),
        migrations.AlterField(
            model_name="instagram",
            name="html",
            field=models.TextField(
                blank=True,
                help_text="Post caption with hashtags & usernames converted to <a> links",
            ),
        ),
        migrations.AlterField(
            model_name="instagram",
            name="image_url",
            field=models.URLField(help_text="Image URL on Instagram", max_length=500),
        ),
        migrations.AlterField(
            model_name="instagram",
            name="text",
            field=models.TextField(blank=True, help_text="Post caption"),
        ),
    ]
