# Generated by Django 5.2.16 on 2026-07-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_delete_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='username',
            field=models.CharField(default='ccalibraries', max_length=30),
        ),
    ]
