files:
    include:
        - libraries/libraries/static/scss/**/*.scss
        - libraries/libraries/static/scss/**/**/*.scss
        - libraries/libraries/static/summon/scss/*.scss
    ignore:
        - libraries/libraries/static/scss/bootstrap/**/*.scss
        - libraries/libraries/static/scss/reset/_reset.scss

rules:
    class-name-format: 0
    colorKeyword: 0
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    hex-notation: 0
    indentation:
        - 1
        -
          size: 4
    mixins-before-declarations: 0
    selector-format: 0
    space-between-parens: 0
    variable-name-format: 0
