linters:

    ColorKeyword:
        enabled: false

    Indentation:
        enabled: true
        width: 4

    SelectorFormat:
        enabled: false

    SpaceBetweenParens:
        enabled: false
