# Generated by Django 2.2.24 on 2021-09-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummonDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, help_text='Date the deleted records were sent to Summon SFTP.')),
                ('number', models.PositiveIntegerField(default=0, help_text='Number of records that we deleted.')),
                ('records', models.TextField(blank=True, help_text='Newline-separated list of deleted record ID numbers ("biblionumber" in Koha parlance).')),
            ],
        ),
    ]
