# Generated by Django 2.2.24 on 2021-09-15 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summon', '0001_summon_deletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summondelete',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date the deleted records were sent to Summon SFTP.'),
        ),
    ]
