# Settings to expose as environment variables.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  labels:
    app: libraries
data:
  CAS_SERVER_URL: https://sso-stage.cca.edu/cas/login

  ES_URL: http://elasticsearch.libraries-wagtail:9200
  ES_INDEX_PREFIX: libraries_wagtail

  # Static files stored in Google Cloud
  # also requires GS_CREDENTIALS in deployment env
  GS_BUCKET_NAME: libraries-media-local

  # local namespace
  LOCAL_NAMESPACE: libraries-wagtail

  # Postgres
  DATABASE_URL: postgres://postgres:admin123@postgres.libraries-wagtail:5432/cca_libraries
  PGHOST: postgres.libraries-wagtail
  PGUSER: postgres
  PGDATABASE: cca_libraries
  PGPASSWORD: admin123
