apiVersion: v1
kind: Service
metadata:
  name: libraries
  labels:
    app: libraries
spec:
  selector:
    app: libraries
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
