# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170726_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='slug',
            field=models.CharField(default='slug', max_length=150),
            preserve_default=False,
        ),
    ]
