# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20170726_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflistpage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Only used in search results right now', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
