# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20170727_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='main_image',
            field=models.ForeignKey(help_text='Will be sized 150-by-150px on the staff list page.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='stafflistpage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Only used in search results right now', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
