# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_protect_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflistpage',
            name='post_script',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text appears below the list of staff.'),
        ),
        migrations.AlterField(
            model_name='stafflistpage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text="Doesn't display on the page itself but a thumbnail close to 230x115px is used on the 'About Us' page and a smaller thumbnail is also used in search results.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='main_image',
            field=models.ForeignKey(help_text='Use a roughly square image; it will be sized 150-by-150px on the staff list page.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
