# Generated by Django 2.0.2 on 2018-08-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_post_script'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafflistpage',
            options={'ordering': ['order', '-last_published_at']},
        ),
        migrations.AddField(
            model_name='stafflistpage',
            name='order',
            field=models.IntegerField(default=1, help_text='Defines the sort order in the parent row (lower numbers go first).'),
        ),
    ]
