# Generated by Django 4.1.13 on 2024-02-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staff_revisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='latest_revision',
        ),
    ]
