apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: es-host-setup
spec:
  selector:
    matchLabels:
      name: es-host-setup
  template:
    metadata:
      labels:
        name: es-host-setup
    spec:
      containers:
      - name: es-host-setup
        image: busybox
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
            sysctl -w vm.max_map_count=262144
            while :; do sleep 3600; done
      restartPolicy: Always
