apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - command:
            - /bin/sh
            - -exc
            - /usr/local/bin/docker-entrypoint.sh eswrapper
          env:
            - name: discovery.type
              value: single-node
          # ! need arm64 images for M2 mac only published by elasticsearch themselves, not on docker hub
          # ! https://www.docker.elastic.co/r/elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3-arm64
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 2048Mi
              cpu: "1"
            requests:
              memory: 2048Mi
              cpu: "1"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      initContainers:
        - command:
            - chown
            - -R
            - 1000:1000
            - /usr/share/elasticsearch/data
          image: busybox
          imagePullPolicy: Always
          name: set-data-owner
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-pv-volumeclaim
