apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - command:
            - /bin/sh
            - -exc
            - "grep xpack.security.enabled /usr/share/elasticsearch/config/elasticsearch.yml || echo 'xpack.security.enabled: false' >> /usr/share/elasticsearch/config/elasticsearch.yml; /usr/local/bin/docker-entrypoint.sh eswrapper"
          env:
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.17.27
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 2048Mi
              cpu: "1"
            requests:
              memory: 2048Mi
              cpu: "1"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      initContainers:
        - command:
            - chown
            - -R
            - 1000:1000
            - /usr/share/elasticsearch/data
          image: busybox
          imagePullPolicy: Always
          name: set-data-owner
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-pv-volumeclaim
