apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-volume
  labels:
    type: local
    app: elasticsearch
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/elasticsearch-pv-volume/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-volumeclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
