apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  # note: actual local db is cca_libraries, this one is empty, what happened here?
  POSTGRES_DB: libraries_wagtail
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-initdb-config
  labels:
    app: postgres
data:
  initdb.sql: |
    CREATE EXTENSION IF NOT EXISTS hstore;
