apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: cca_libraries
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-initdb-config
  labels:
    app: postgres
data:
  initdb.sql: |
    CREATE EXTENSION IF NOT EXISTS hstore;
