apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  PGDATABASE: cca_libraries
  PGUSER: postgresadmin
  PGPASSWORD: admin123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-initdb-config
  labels:
    app: postgres
data:
  initdb.sql: |
    CREATE EXTENSION IF NOT EXISTS hstore;
