apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  # why is this NodePort and not ClusterIP? Is it needed outside the cluster?
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
