---
# this is the file used by [ep|mg]-full-... tagged releases
# create the namespace for libraries

kind: Namespace
apiVersion: v1
metadata:
  name: ${KUBERNETES_NAMESPACE_OVERWRITE}
  labels:
    name: libraries

---
# Settings to expose as environment variables.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
data:
  # TODO review k8s secrets — some are unused (secret-key) and others should be converted to Secret Manager
  # Generic
  DJANGO_SETTINGS_MODULE: libraries.settings
  KUBERNETES_NAMESPACE: ${KUBERNETES_NAMESPACE_OVERWRITE}

  # CAS
  CAS_SERVER_URL: "https://sso5-stage.cca.edu/cas/login"

  # Media
  MEDIA_URL: "https://storage.googleapis.com/libraries-staging-${KUBERNETES_NAMESPACE_OVERWRITE}/"

  # Review Apps
  DEPLOY_RELEASE: ${KUBERNETES_NAMESPACE_OVERWRITE}
  # DEPLOY_RELEASE: ${CI_COMMIT_REF_NAME}
  # DEPLOY_COMMIT_HASH: ${CI_COMMIT_SHORT_SHA}
  # DEPLOY_BRANCH_NAME: ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
  # DEPLOY_SERVER_NAME: ${KUBERNETES_NAMESPACE_OVERWRITE}

  # Elastic Search
  ES_INDEX_PREFIX: ${KUBERNETES_NAMESPACE_OVERWRITE}

  # Google Cloud Storage
  GS_PROJECT_ID: cca-web-staging
  GS_BUCKET_NAME: libraries-media-staging-${KUBERNETES_NAMESPACE_OVERWRITE}

  # Database
  DB_NAME: libraries-${KUBERNETES_NAMESPACE_OVERWRITE}

---
# The application itself.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
spec:
  # Start 1 copy of the application.
  replicas: 1
  # Select the pods which are part of this deployment.
  selector:
    matchLabels:
      app: libraries
  # The pod template this deployment will create.
  template:
    metadata:
      labels:
        app: libraries
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      initContainers:
        - name: init-app
          image: us.gcr.io/cca-web-staging/libraries:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
          imagePullPolicy: Always
          command:
            [
              "sh",
              "-c",
              "python manage.py migrate --noinput && python manage.py createcachetable",
            ]
          # Env variables form ConfigMap
          envFrom:
            - configMapRef:
                name: app
          env:
            # ! removing these causes the pod to never start even though we should get them via Secret Manager
            # Database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DATABASE_URL
              value: postgres://$(DB_USER):$(DB_PASSWORD)@cloudsqlproxy:5432/$(DB_NAME)
            # Google Cloud Storage
            - name: GS_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: cloud-storage-credentials
                  key: credentials
      containers:
        - name: app
          image: us.gcr.io/cca-web-staging/libraries:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
          imagePullPolicy: Always
          # Env variables form ConfigMap
          envFrom:
            - configMapRef:
                name: app
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DATABASE_URL
              value: postgres://$(DB_USER):$(DB_PASSWORD)@cloudsqlproxy:5432/$(DB_NAME)
            # Google Cloud Storage
            - name: GS_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: cloud-storage-credentials
                  key: credentials
          # Define the port our application listens on.
          ports:
            - containerPort: 8000
          # Lower resource requests & limits for staging
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

---
# Cloud SQL proxy
# We need this to access our Cloud SQL instance(s)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsqlproxy
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
spec:
  replicas: 1
  # Select the pods which are part of this deployment.
  selector:
    matchLabels:
      tool: cloudsqlproxy
  # The pod template this deployment will create.
  template:
    metadata:
      labels:
        tool: cloudsqlproxy
    spec:
      containers:
        - name: cloudsqlproxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.26.0
          command:
            [
              "/cloud_sql_proxy",
              "--dir=/cloudsql",
              "-instances=cca-web-staging:us-west1:psql14-instance=tcp:0.0.0.0:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          ports:
            - name: postgresql
              containerPort: 5432
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: cloudsql
              mountPath: /cloudsql
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir: {}

---
# A service to allow external connections.  This accepts connections from inside
# the cluster and distributes them to our pod(s).
apiVersion: v1
kind: Service
metadata:
  name: libraries-http
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
  labels:
    app: libraries
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app: libraries

---
# A service that allows pods to connect to the Cloud SQL instance
# via cloudsqlproxy pod(s)
apiVersion: v1
kind: Service
metadata:
  name: cloudsqlproxy
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
spec:
  ports:
    - port: 5432
      targetPort: postgresql
  selector:
    tool: cloudsqlproxy

---
## Ingress to configure external connections.  On GKE, this will create a GCP
## HTTP load balancer.  These are charged *per ingress* so be careful when
## creating new ones.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
spec:
  defaultBackend:
    service:
      name: libraries-http
      port:
        number: 8000

---
#
# CRONJOBS
#
# All our cronjobs are suspended (spec.suspend = true) on staging
# Edit their schedule to run soon & unsuspend when testing.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: summon-sftp
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
spec:
  suspend: true
  # times are UTC
  schedule: "30 20 * * *"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  # https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically
  # Our server k8s does not support this yet
  # ttlSecondsAfterFinished: 900
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: libraries
        spec:
          restartPolicy: Never
          volumes:
            - name: summon-sftp-secrets
              secret:
                secretName: summon-sftp-secrets
          containers:
            - name: summon
              image: us.gcr.io/cca-web-staging/libraries:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
              imagePullPolicy: IfNotPresent
              args:
                - python
                - manage.py
                - summon_deletes
              volumeMounts:
                - name: summon-sftp-secrets
                  readOnly: true
                  mountPath: /root/.ssh
              # Env variables form ConfigMap
              envFrom:
                - configMapRef:
                    name: app
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: password
                - name: DATABASE_URL
                  value: postgres://$(DB_USER):$(DB_PASSWORD)@cloudsqlproxy:5432/$(DB_NAME)
                - name: GS_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name: cloud-storage-credentials
                      key: credentials

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: instagram
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
spec:
  suspend: true
  # times are UTC
  schedule: "10 19 * * *"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  # ttlSecondsAfterFinished: 900
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: libraries
        spec:
          restartPolicy: Never
          containers:
            - name: instagram
              image: us.gcr.io/cca-web-staging/libraries:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
              imagePullPolicy: IfNotPresent
              args:
                - python
                - manage.py
                - instagram
              # Env variables form ConfigMap
              envFrom:
                - configMapRef:
                    name: app
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: password
                - name: DATABASE_URL
                  value: postgres://$(DB_USER):$(DB_PASSWORD)@cloudsqlproxy:5432/$(DB_NAME)
                - name: GS_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name: cloud-storage-credentials
                      key: credentials

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: publish-scheduled-pages
  namespace: ${KUBERNETES_NAMESPACE_OVERWRITE}
spec:
  suspend: true
  # run hourly at half-past
  schedule: "30 * * * *"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  # ttlSecondsAfterFinished: 900
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: libraries
        spec:
          restartPolicy: Never
          containers:
            - name: publish-scheduled-pages
              image: us.gcr.io/cca-web-staging/libraries:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
              imagePullPolicy: IfNotPresent
              args:
                - python
                - manage.py
                - publish_scheduled_pages
              # Env variables form ConfigMap
              envFrom:
                - configMapRef:
                    name: app
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cloudsql-db-credentials
                      key: password
                - name: DATABASE_URL
                  value: postgres://$(DB_USER):$(DB_PASSWORD)@cloudsqlproxy:5432/$(DB_NAME)
                - name: GS_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name: cloud-storage-credentials
                      key: credentials
