# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170802_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Try to ALWAYS provide a main image.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
