# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_richtext_editor_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Resized to 400x267px for the home page thumbnail and 700px wide on the post itself with a preserved aspect ratio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
