# Generated by Django 2.2.4 on 2019-10-31 19:26
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="This should be the same as the Portal ID.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "alert_text",
                    models.TextField(
                        help_text="Add text that will appear on the alert bannner. Maximum 500 characters"
                    ),
                ),
                (
                    "alert_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional link to portal.cca.edu alert page.",
                        null=True,
                    ),
                ),
                (
                    "alert_link_text",
                    models.CharField(
                        default="More Info",
                        help_text="The text that will appear in the alert banner or the link to this Alert Page, if applicable.",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
