# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20170727_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='fri',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='mon',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='satur',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='sun',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='thurs',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='tues',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='wednes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
