# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0004_auto_20170727_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='closure',
            name='explanation',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='closure',
            name='end_date',
            field=models.DateField(help_text='can be the same as start date', verbose_name='End Date'),
        ),
    ]
