# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0008_protect_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourspage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text="Doesn't display on the page itself but a thumbnail close to 230x115px is used on the 'About Us' page and a smaller thumbnail is also used in search results.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
