# Generated by Django 2.0.2 on 2018-03-14 23:18

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0009_staff_post_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='explanation',
            field=wagtail.fields.RichTextField(blank=True, help_text='This is a staff-facing field only right now.'),
        ),
    ]
