# Generated by Django 3.2.15 on 2022-08-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0011_page-ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='label',
            field=models.CharField(help_text='e.g. Simpson Fall 2022', max_length=200),
        ),
    ]
