# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_servicepage_servicesrowpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesrowpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='servicesrowpage',
            name='sort_order',
        ),
    ]
