# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20170719_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesrowpage',
            name='summary',
            field=models.CharField(max_length=350),
        ),
    ]
