# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 00:36
from __future__ import unicode_literals

from django.db import migrations
from wagtail.wagtailcore.models import Page


# create the initial About Us, Collections, and Services pages
def create_categories(apps, schema_editor):
    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')
    AboutUsPage = apps.get_model('categories.AboutUsPage')
    CollectionsPage = apps.get_model('categories.CollectionsPage')
    ServicesPage = apps.get_model('categories.ServicesPage')

    # Delete any existing blogindex
    # Protects if migration is run multiple times
    AboutUsPage.objects.filter(slug='about-us', depth=3).delete()
    CollectionsPage.objects.filter(slug='collections', depth=3).delete()
    ServicesPage.objects.filter(slug='services', depth=3).delete()

    # Get content type for blogindex model
    aboutuspage_content_type, __ = ContentType.objects.get_or_create(
        model='aboutuspage', app_label='categories')
    collectionspage_content_type, __ = ContentType.objects.get_or_create(
        model='collectionspage', app_label='categories')
    servicespage_content_type, __ = ContentType.objects.get_or_create(
        model='servicespage', app_label='categories')

    home_page = Page.objects.get(slug='home')

    about_us = AboutUsPage(
        title="About Us",
        slug='about-us',
        content_type=aboutuspage_content_type,
        depth=3,
        url_path='/home/about-us/'
    )
    collections = CollectionsPage(
        title="Collections",
        slug='collections',
        content_type=collectionspage_content_type,
        depth=3,
        url_path='/home/collections/'
    )
    services = ServicesPage(
        title="Services",
        slug='services',
        content_type=servicespage_content_type,
        depth=3,
        url_path='/home/service/'
    )

    # Create a new blogindex as child of home page
    home_page.add_child(instance=about_us)
    home_page.add_child(instance=collections)
    home_page.add_child(instance=services)


def remove_categories(apps, schema_editor):
    # Get models
    AboutUsPage = apps.get_model('categories.AboutUsPage')
    CollectionsPage = apps.get_model('categories.CollectionsPage')
    ServicesPage = apps.get_model('categories.ServicesPage')

    # Delete the default blogindex
    # Page and Site objects CASCADE
    AboutUsPage.objects.filter(slug='about-us', depth=3).delete()
    CollectionsPage.objects.filter(slug='collections', depth=3).delete()
    ServicesPage.objects.filter(slug='services', depth=3).delete()


class Migration(migrations.Migration):
    # we need the category models to already exist
    dependencies = [
        ('categories', '0005_auto_20170719_1924'),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
