# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('categories', '0005_auto_20170719_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('blurb', wagtail.fields.RichTextField()),
                ('link', models.URLField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='CollectionsPage',
            new_name='CategoryPage',
        ),
        migrations.RenameModel(
            old_name='ServicesRowPage',
            new_name='RowComponent',
        ),
        migrations.RenameModel(
            old_name='ServicesPage',
            new_name='SpecialCollectionsPage',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='page',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='specialcollection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_collections', to='categories.SpecialCollectionsPage'),
        ),
    ]
