# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:15
from __future__ import unicode_literals

import categories.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('categories', '0009_create_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='body',
            field=wagtail.core.fields.StreamField((('subheading', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock())))), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('snippet', wagtail.core.blocks.RichTextBlock()), ('html', categories.models.EmbedHTML(label='Embed code'))), null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Try to ALWAYS provide a main image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.core.fields.StreamField((('subheading', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock())))), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('snippet', wagtail.core.blocks.RichTextBlock()), ('html', categories.models.EmbedHTML(label='Embed code'))), null=True),
        ),
    ]
