# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:30
from __future__ import unicode_literals

import categories.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20170721_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='body',
            field=wagtail.core.fields.StreamField((('subheading', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock())))), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('snippet', wagtail.core.blocks.RichTextBlock()), ('html', categories.models.EmbedHTML(label='Embed code'))), null=True, verbose_name='Page content'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.core.fields.StreamField((('subheading', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock())))), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('snippet', wagtail.core.blocks.RichTextBlock()), ('html', categories.models.EmbedHTML(label='Embed code'))), null=True, verbose_name='Page content'),
        ),
    ]
