# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20170726_2337'),
        ('categories', '0013_aboutus_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Optional associated staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.StaffMember'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Optional associated staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.StaffMember'),
        ),
    ]
