# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:28
from __future__ import unicode_literals

import categories.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_auto_20170726_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('subheading', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title', template='categories/blocks/subheading.html')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', template='categories/blocks/paragraph.html')), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(blank=True))))), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('quote title')), ('name', wagtail.wagtailcore.blocks.CharBlock(blank=True)), ('position', wagtail.wagtailcore.blocks.CharBlock(blank=True, label='Position or affiliation'))))), ('snippet', wagtail.wagtailcore.blocks.RichTextBlock(label='Callout', template='categories/blocks/snippet.html')), ('html', categories.models.EmbedHTML(label='Embed code'))), null=True, verbose_name='Page content'),
        ),
        migrations.AlterField(
            model_name='specialcollection',
            name='image',
            field=models.ForeignKey(blank=True, help_text='2x1 aspect ratio preferred, will be sized to 910x400px at its largest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
