# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20170727_1628'),
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('categories', '0015_auto_20170727_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('link', models.URLField()),
                ('main_image', models.ForeignKey(blank=True, help_text='Used in search results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('staff', models.ForeignKey(blank=True, help_text='Optional associated staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.StaffMember')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
