# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_auto_20170802_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Try to ALWAYS provide a main image.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Used in search results', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Try to ALWAYS provide a main image.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='specialcollection',
            name='image',
            field=models.ForeignKey(blank=True, help_text='2x1 aspect ratio preferred, will be sized to 910x400px at its largest.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
