# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_auto_20170807_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'Simple text page'},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Complex text page'},
        ),
    ]
