# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_auto_20170808_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcollection',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
