# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0024_richtext_editor_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowcomponent',
            name='summary',
            field=wagtail.fields.RichTextField(),
        ),
    ]
