# Generated by Django 2.0.2 on 2018-06-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0026_staff_post_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcollection',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Close to a 2.25-by-1 aspect ratio is bst, image is sized to 910x400px at its largest.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
