# Generated by Django 2.0.2 on 2018-06-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0027_SpecialCollection_image_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='display_staff_card',
            field=models.BooleanField(default=False, help_text='Display a small "card" showing contact information for the associated staff member.'),
        ),
    ]
