# Generated by Django 2.0.2 on 2018-06-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0028_staff-display-boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='display_staff_card',
            field=models.BooleanField(default=False, help_text='Display a small "card" showing contact information for the associated staff member.'),
        ),
    ]
