# Generated by Django 2.0.2 on 2018-08-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0030_row-distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'ordering': ['order', '-last_published_at'], 'verbose_name': 'Simple text page'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['order', '-last_published_at']},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'ordering': ['order', '-last_published_at'], 'verbose_name': 'Complex text page'},
        ),
        migrations.AlterModelOptions(
            name='specialcollectionspage',
            options={'ordering': ['order', '-last_published_at']},
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='order',
            field=models.IntegerField(default=1, help_text='Defines the sort order in the parent row (lower numbers go first).'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='order',
            field=models.IntegerField(default=1, help_text='Defines the sort order in the parent row (lower numbers go first).'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='order',
            field=models.IntegerField(default=1, help_text='Defines the sort order in the parent row (lower numbers go first).'),
        ),
        migrations.AddField(
            model_name='specialcollectionspage',
            name='order',
            field=models.IntegerField(default=1, help_text='Defines the sort order in the parent row (lower numbers go first).'),
        ),
    ]
