# Generated by Django 2.2.4 on 2019-08-08 19:57

import categories.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0032_richtext_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'Simple text page'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Complex text page'},
        ),
        migrations.AlterModelOptions(
            name='specialcollectionspage',
            options={},
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='resources',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True, null=True, verbose_name='List of resource links'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='sidebar_cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text="Square, resized to 400x400. If you don't specify an image & select a Page below, the Page's Main Image will be used.", required=False)), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Internal web page', required=False))]))]))], blank=True, null=True, verbose_name='Cards in the right-hand column'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='resources',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Internal web page', required=False))]))], blank=True, null=True, verbose_name='List of resource links'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sidebar_cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text="Square, resized to 400x400. If you don't specify an image & select a Page below, the Page's Main Image will be used.", required=False)), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Internal web page', required=False))]))]))], blank=True, null=True, verbose_name='Cards in the right-hand column'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.core.fields.StreamField([('subheading', wagtail.core.blocks.CharBlock(classname='title', icon='title', template='categories/blocks/subheading.html')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript', 'code', 'embed', 'h3', 'hr', 'image', 'ol', 'ul'], icon='pilcrow', template='categories/blocks/paragraph.html')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript'], required=False))])), ('linked_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript'], required=False)), ('link', wagtail.core.blocks.URLBlock())])), ('card', wagtail.core.blocks.StructBlock([('thumbnail', wagtail.images.blocks.ImageChooserBlock(help_text='Should be 3x2 aspect ratio but may be stretched if used in a row without an equal distribution. Resized to roughly 345x230.')), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Internal web page', required=False))])), ('body', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript']))])), ('pullquote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock('quote title')), ('name', wagtail.core.blocks.CharBlock(required=False)), ('position', wagtail.core.blocks.CharBlock(label='Position or affiliation', required=False))])), ('snippet', wagtail.core.blocks.RichTextBlock(label='Callout', template='categories/blocks/snippet.html')), ('html', categories.models.EmbedHTML(label='Embed code')), ('row', wagtail.core.blocks.StreamBlock([('distribution', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[('left', 'left side bigger'), ('right', 'right side bigger'), ('equal', 'equal size sides')], max_num=1, min_num=1)), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript', 'code', 'embed', 'h3', 'hr', 'image', 'ol', 'ul'], icon='pilcrow', template='categories/blocks/paragraph.html')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript'], required=False))])), ('linked_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript'], required=False)), ('link', wagtail.core.blocks.URLBlock())])), ('card', wagtail.core.blocks.StructBlock([('thumbnail', wagtail.images.blocks.ImageChooserBlock(help_text='Should be 3x2 aspect ratio but may be stretched if used in a row without an equal distribution. Resized to roughly 345x230.')), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Internal web page', required=False))])), ('body', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript']))])), ('pullquote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock('quote title')), ('name', wagtail.core.blocks.CharBlock(required=False)), ('position', wagtail.core.blocks.CharBlock(label='Position or affiliation', required=False))])), ('snippet', wagtail.core.blocks.RichTextBlock(features=['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript', 'code', 'embed', 'h3', 'hr', 'image', 'ol', 'ul'], label='Callout', template='categories/blocks/snippet.html'))], max_num=3))], null=True, verbose_name='Page content'),
        ),
    ]
