# Generated by Django 5.2.16 on 2026-07-31 18:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0036_streamfield_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='sidebar_cards',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'help_text': "Square, resized to 400x400. If you don't specify an image & select a Page below, the Page's Main Image will be used."}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Link text', 'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal web page', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('external_url', 2), ('page', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('link', 4)]], {})}, null=True, verbose_name='Cards in the right-hand column'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.fields.StreamField([('subheading', 0), ('paragraph', 1), ('linked_image', 6), ('card', 12), ('image_grid', 16), ('pullquote', 20), ('snippet', 21), ('html', 22), ('row', 25), ('table', 26)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'categories/blocks/subheading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript', 'code', 'embed', 'h3', 'hr', 'image', 'ol', 'ul'], 'icon': 'pilcrow', 'template': 'categories/blocks/paragraph.html'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript'], 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': "Only one of these (external URL or internal page) is needed. You can leave both blank if you don't want the image to be linked.", 'label': 'External URL', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal web page', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('external_url', 4), ('page', 5)]], {}), 7: ('wagtail.images.blocks.ImageBlock', [], {'help_text': 'Should be 3x2 aspect ratio but may be stretched if used in a row without an equal distribution. Resized to roughly 345x230.'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Link text', 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('external_url', 9), ('page', 5)]], {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript']}), 12: ('wagtail.blocks.StructBlock', [[('thumbnail', 7), ('link', 10), ('body', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': 'Maximum: 30 characters', 'max_length': 30, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Text will be truncated if input (including title) exceeds allotted space.'}), 15: ('wagtail.blocks.StructBlock', [[('image', 2), ('external_url', 4), ('page', 5), ('title', 13), ('caption', 14)]], {}), 16: ('categories.models.blocks.ProductGridBlock', (15,), {'label': 'Image grid'}), 17: ('wagtail.blocks.TextBlock', (), {}), 18: ('wagtail.blocks.CharBlock', (), {'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Position or affiliation', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('quote', 17), ('name', 18), ('position', 19)]], {}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Callout', 'template': 'categories/blocks/snippet.html'}), 22: ('categories.models.blocks.EmbedHTML', (), {'label': 'Embed code'}), 23: ('wagtail.blocks.ChoiceBlock', [], {'blank': False, 'choices': [('left', 'left side bigger'), ('right', 'right side bigger'), ('equal', 'equal size sides')], 'max_num': 1, 'min_num': 1}), 24: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'document-link', 'italic', 'link', 'strikethrough', 'subscript', 'superscript', 'code', 'embed', 'h3', 'hr', 'image', 'ol', 'ul'], 'label': 'Callout', 'template': 'categories/blocks/snippet.html'}), 25: ('wagtail.blocks.StreamBlock', [[('distribution', 23), ('paragraph', 1), ('linked_image', 6), ('card', 12), ('pullquote', 20), ('snippet', 24)]], {'max_num': 3}), 26: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}, null=True, verbose_name='Page content'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='sidebar_cards',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'help_text': "Square, resized to 400x400. If you don't specify an image & select a Page below, the Page's Main Image will be used."}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Link text', 'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal web page', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('external_url', 2), ('page', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('link', 4)]], {})}, null=True, verbose_name='Cards in the right-hand column'),
        ),
    ]
