#!/usr/bin/env fish
argparse -n sync.fish --exclusive s,p s/stage p/prod h/help -- $argv

if set -q _flag_h
    echo 'Usage: gsb-cache [ -s, --stage | -p, --prod ]'
    echo 'Adds Cache-Control metadata ("Cache-Control: public, max-age31536000") to all
files in the /images/ folder of the specified (staging or production) Google
Storage Bucket.'
    exit 0
end

if not set -q _flag_p; and not set -q _flag_s
    echo "Error: must specify either a staging or production context."
    echo "Use the -s or -p flags"
    exit 1
end

if set -q _flag_p
    set URL gs://libraries-lib-production/images
end

if set -q _flag_s
    set URL gs://libraries-media-staging-lib-ep/images
end

gsutil -m setmeta -h "Cache-Control: public, max-age=31536000" "$URL/*"
